### ISSUE TITLE
Existing attribute already has name xxx

### ISSUE THREAD

**Issue by GiliKallner** [michaelduminy/serverless-cognito-add-custom-attributes#3]
Hi,

Thank you so much for this great plugin! 

I'm new to aws and tried to use your plugin in combination with the appsync-serverless-plugin but came upon an issue I hope you can help me fix.

After replacing my userpool configurations in the serverless.yml I got this error:
  
```
Serverless: CognitoAddCustomAttributesPlugin: Start
Serverless: CognitoAddCustomAttributesPlugin: Found userPoolId: xxxxx
Serverless: CognitoAddCustomAttributesPlugin: Found userPoolClientId: xxxxx
Serverless: CognitoAddCustomAttributesPlugin: Adding 1 attribute(s) to pool: custom:name
Serverless: CognitoAddCustomAttributesPlugin: Error occurred when adding attributes to pool. CognitoAddCustomAttributesPluginError: custom:custom:name: Existing attribute already has name custom:custom:name.
```
The userpool mentioned above does exist in the aws console and I can get it in the terminal with this line of code, and see that it actually has the above mentioned attributes:
```
aws cognito-idp describe-user-pool --user-pool-id xxxx
```

Looking at the source code I see that this plugin is filtering the results from the existing userpool and only adds new attributes when those do not exists in the existing one but as you can see - that doesn't work for me.

Can you please help me?

Thanks a lot

Gili

**Comment by jmaleonard** [comment]
Name is reserved so you cannot add that as a custom name. It exists on default on the user pool

**Comment by GiliKallner** [comment]
@jmaleonard, ok, I understand. Thanks for you response.

I'm a little new to this and didn't want to add the name because on the console it presents it in the required fields section. 

Do you by chance know how to set the name value with serverless and make it not mendatory? 

Thanks a lot.

**Comment by jmaleonard** [comment]
Please see https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html
