### ISSUE TITLE
Successfully deployed but no custom attribute defined

### ISSUE THREAD

**Issue by adrianmaurer** [michaelduminy/serverless-cognito-add-custom-attributes#5]
Would there be any reason why the addition of a custom attribute would not appear in the attributes section of the Cognito user pool after being defined? (see log)

```
Serverless: CognitoAddCustomAttributesPlugin: Start
Serverless: [AWS cloudformation 200 0.224s 0 retries] describeStacks({ StackName: [redacted]})
Serverless: CognitoAddCustomAttributesPlugin: Found userPoolId: [redacted]
Serverless: CognitoAddCustomAttributesPlugin: End
Serverless: CognitoAddCustomAttributesPlugin: Found userPoolClientId: [redacted]
Serverless: Invoke aws:deploy:finalize
Serverless: [AWS s3 200 0.218s 0 retries] listObjectsV2({ Bucket:
   [redacted],
  Prefix: [redacted] })
Serverless: Removing old service artifacts from S3...
Serverless: [AWS cognitoidentityserviceprovider 200 0.244s 0 retries] describeUserPool({ UserPoolId: [redacted]})
Serverless: [AWS cognitoidentityserviceprovider 200 0.152s 0 retries] describeUserPoolClient({ ClientId: '***SensitiveInformation***',
  UserPoolId: [redacted]})
Serverless: CognitoAddCustomAttributesPlugin: Adding 1 attribute(s) to pool: subscription
```

```
Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           11.5.0
     Serverless Version:     1.39.1
```

**Comment by angeloglirazan** [comment]
I have the same problem; no change shows in my user pool. Below are my logs. After the following lines, execution ends.
`
Serverless: CognitoAddCustomAttributesPlugin: Start
Serverless: CognitoAddCustomAttributesPlugin: Found userPoolId: [redacted]
Serverless: CognitoAddCustomAttributesPlugin: End
Serverless: CognitoAddCustomAttributesPlugin: Found userPoolClientId: [redacted]
Serverless: Removing old service artifacts from S3...
Serverless: CognitoAddCustomAttributesPlugin: Adding 1 attribute(s) to pool: store_id
`

Here is my environment:
`
Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.0.0
     Serverless Version:     1.35.1
`

**Comment by adrianmaurer** [comment]
Seemed to work after I tore down the entire deploy
